Traceback (most recent call last):
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\Users\Christina\Programmes\envs\GRACE_GPU\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
# caution: path[0] is reserved for script path (or '' in REPL)
#sys.path.append('../sentiment-analysis/GRACE/')
sys.path.insert(0, '../GRACE/') # map to other folder with all GRACE training files

import torch
import os
from ate_asc_modeling_local_bert_file import BertForSequenceLabeling
import ate_asc_modeling_local_bert_file
from file_utils import PYTORCH_PRETRAINED_BERT_CACHE
from ate_asc_features import ATEASCProcessor, convert_examples_to_features, get_labels
from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler, TensorDataset)
from tokenization import BertTokenizer
import argparse
import random
import time
import numpy as np
import torch.nn.functional as F

import csv
import urllib.request
import pandas as pd                                                    # data handling
import xml.etree.cElementTree as ET                                    # XML file parsing
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 8[0m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mate_asc_modeling_local_bert_file[39;00m [38;5;28;01mimport[39;00m BertForSequenceLabeling
[0;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mate_asc_modeling_local_bert_file[39;00m
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mfile_utils[39;00m [38;5;28;01mimport[39;00m PYTORCH_PRETRAINED_BERT_CACHE

File [1;32mD:\Users\Christina\Documents\gitlab_vscode\github\SA_book\book\ate_asc_modeling_local_bert_file.py:36[0m
[0;32m     34[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnn[39;00m [38;5;28;01mimport[39;00m CrossEntropyLoss
[0;32m     35[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfunctional[39;00m [38;5;28;01mas[39;00m [38;5;21;01mF[39;00m
[1;32m---> 36[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdecoder_module[39;00m [38;5;28;01mimport[39;00m PreTrainedDecoderBertModel, DecoderBertModel
[0;32m     37[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m get_aspect_chunks
[0;32m     39[0m [38;5;28;01mfrom[39;00m [38;5;21;01mweighted_cross_entropy[39;00m [38;5;28;01mimport[39;00m WeightedCrossEntropy

[1;31mModuleNotFoundError[0m: No module named 'decoder_module'
ModuleNotFoundError: No module named 'decoder_module'

